// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using RivianMate.Infrastructure.Data;

#nullable disable

namespace RivianMate.Infrastructure.Data.Migrations
{
    [DbContext(typeof(RivianMateDbContext))]
    [Migration("20260122234701_AddBroadcastEmail")]
    partial class AddBroadcastEmail
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.DataProtection.EntityFrameworkCore.DataProtectionKey", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("FriendlyName")
                        .HasColumnType("text");

                    b.Property<string>("Xml")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("DataProtectionKeys");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("text");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("Value")
                        .HasColumnType("text");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("RivianMate.Core.Entities.ActivityFeedItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.Property<int>("VehicleId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Timestamp");

                    b.HasIndex("VehicleId", "Timestamp");

                    b.HasIndex("VehicleId", "Type", "Timestamp");

                    b.ToTable("ActivityFeed");
                });

            modelBuilder.Entity("RivianMate.Core.Entities.ApplicationUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DisplayName")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("LastLoginAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("RivianMate.Core.Entities.BatteryHealthSnapshot", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<double>("CapacityLostKwh")
                        .HasColumnType("double precision");

                    b.Property<double>("DegradationPercent")
                        .HasColumnType("double precision");

                    b.Property<double?>("DegradationRatePer10kMiles")
                        .HasColumnType("double precision");

                    b.Property<double>("HealthPercent")
                        .HasColumnType("double precision");

                    b.Property<double>("Odometer")
                        .HasColumnType("double precision");

                    b.Property<double>("OriginalCapacityKwh")
                        .HasColumnType("double precision");

                    b.Property<double?>("ProjectedHealthAt100kMiles")
                        .HasColumnType("double precision");

                    b.Property<double?>("ProjectedMilesTo70Percent")
                        .HasColumnType("double precision");

                    b.Property<double?>("ReadingConfidence")
                        .HasColumnType("double precision");

                    b.Property<double?>("RemainingWarrantyCapacityKwh")
                        .HasColumnType("double precision");

                    b.Property<double>("ReportedCapacityKwh")
                        .HasColumnType("double precision");

                    b.Property<double?>("SmoothedCapacityKwh")
                        .HasColumnType("double precision");

                    b.Property<double?>("SmoothedHealthPercent")
                        .HasColumnType("double precision");

                    b.Property<double?>("StateOfCharge")
                        .HasColumnType("double precision");

                    b.Property<double?>("Temperature")
                        .HasColumnType("double precision");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("VehicleId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Timestamp");

                    b.HasIndex("VehicleId", "Timestamp");

                    b.ToTable("BatteryHealthSnapshots");
                });

            modelBuilder.Entity("RivianMate.Core.Entities.BroadcastEmail", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<Guid>("AdminUserId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("FailedCount")
                        .HasColumnType("integer");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(10000)
                        .HasColumnType("character varying(10000)");

                    b.Property<int>("SentCount")
                        .HasColumnType("integer");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int>("TotalRecipients")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("AdminUserId");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("Status");

                    b.ToTable("BroadcastEmails");
                });

            modelBuilder.Entity("RivianMate.Core.Entities.ChargingSession", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<double?>("AveragePowerKw")
                        .HasColumnType("double precision");

                    b.Property<double?>("CalculatedCapacityKwh")
                        .HasColumnType("double precision");

                    b.Property<double?>("CapacityConfidence")
                        .HasColumnType("double precision");

                    b.Property<double?>("ChargeLimit")
                        .HasColumnType("double precision");

                    b.Property<int>("ChargeType")
                        .HasColumnType("integer");

                    b.Property<double?>("Cost")
                        .HasColumnType("double precision");

                    b.Property<string>("DriveMode")
                        .HasColumnType("text");

                    b.Property<double?>("EndBatteryLevel")
                        .HasColumnType("double precision");

                    b.Property<double?>("EndRangeEstimate")
                        .HasColumnType("double precision");

                    b.Property<DateTime?>("EndTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<double?>("EnergyAddedKwh")
                        .HasColumnType("double precision");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool?>("IsHomeCharging")
                        .HasColumnType("boolean");

                    b.Property<double?>("Latitude")
                        .HasColumnType("double precision");

                    b.Property<string>("LocationName")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<double?>("Longitude")
                        .HasColumnType("double precision");

                    b.Property<double?>("OdometerAtStart")
                        .HasColumnType("double precision");

                    b.Property<double?>("PeakPowerKw")
                        .HasColumnType("double precision");

                    b.Property<double?>("RangeAdded")
                        .HasColumnType("double precision");

                    b.Property<double>("StartBatteryLevel")
                        .HasColumnType("double precision");

                    b.Property<double?>("StartRangeEstimate")
                        .HasColumnType("double precision");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<double?>("TemperatureAtStart")
                        .HasColumnType("double precision");

                    b.Property<int>("VehicleId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("IsActive");

                    b.HasIndex("StartTime");

                    b.HasIndex("VehicleId", "StartTime");

                    b.ToTable("ChargingSessions");
                });

            modelBuilder.Entity("RivianMate.Core.Entities.Drive", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<double?>("AverageSpeedMph")
                        .HasColumnType("double precision");

                    b.Property<double?>("AverageTemperature")
                        .HasColumnType("double precision");

                    b.Property<double?>("DistanceMiles")
                        .HasColumnType("double precision");

                    b.Property<string>("DriveMode")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("DriverName")
                        .HasColumnType("text");

                    b.Property<double?>("EfficiencyMilesPerKwh")
                        .HasColumnType("double precision");

                    b.Property<double?>("EfficiencyWhPerMile")
                        .HasColumnType("double precision");

                    b.Property<double?>("ElevationGain")
                        .HasColumnType("double precision");

                    b.Property<string>("EndAddress")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<double?>("EndBatteryLevel")
                        .HasColumnType("double precision");

                    b.Property<double?>("EndElevation")
                        .HasColumnType("double precision");

                    b.Property<double?>("EndLatitude")
                        .HasColumnType("double precision");

                    b.Property<double?>("EndLongitude")
                        .HasColumnType("double precision");

                    b.Property<double?>("EndOdometer")
                        .HasColumnType("double precision");

                    b.Property<double?>("EndRangeEstimate")
                        .HasColumnType("double precision");

                    b.Property<DateTime?>("EndTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<double?>("EnergyUsedKwh")
                        .HasColumnType("double precision");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<double?>("MaxSpeedMph")
                        .HasColumnType("double precision");

                    b.Property<string>("StartAddress")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<double>("StartBatteryLevel")
                        .HasColumnType("double precision");

                    b.Property<double?>("StartElevation")
                        .HasColumnType("double precision");

                    b.Property<double?>("StartLatitude")
                        .HasColumnType("double precision");

                    b.Property<double?>("StartLongitude")
                        .HasColumnType("double precision");

                    b.Property<double>("StartOdometer")
                        .HasColumnType("double precision");

                    b.Property<double?>("StartRangeEstimate")
                        .HasColumnType("double precision");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("VehicleId")
                        .HasColumnType("integer");

                    b.Property<string>("WheelConfig")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("IsActive");

                    b.HasIndex("StartTime");

                    b.HasIndex("VehicleId", "StartTime");

                    b.ToTable("Drives");
                });

            modelBuilder.Entity("RivianMate.Core.Entities.EmailLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ErrorMessage")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("ProviderMessageId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<bool>("Success")
                        .HasColumnType("boolean");

                    b.Property<string>("ToAddress")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("Trigger")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("Trigger");

                    b.HasIndex("UserId");

                    b.ToTable("EmailLogs");
                });

            modelBuilder.Entity("RivianMate.Core.Entities.GeocodingCache", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("City")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Country")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<double>("Latitude")
                        .HasColumnType("double precision");

                    b.Property<double>("Longitude")
                        .HasColumnType("double precision");

                    b.Property<string>("ShortAddress")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("State")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("Latitude", "Longitude")
                        .IsUnique();

                    b.ToTable("GeocodingCache");
                });

            modelBuilder.Entity("RivianMate.Core.Entities.Position", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<double?>("Altitude")
                        .HasColumnType("double precision");

                    b.Property<double?>("BatteryLevel")
                        .HasColumnType("double precision");

                    b.Property<int>("DriveId")
                        .HasColumnType("integer");

                    b.Property<int>("Gear")
                        .HasColumnType("integer");

                    b.Property<double?>("Heading")
                        .HasColumnType("double precision");

                    b.Property<double>("Latitude")
                        .HasColumnType("double precision");

                    b.Property<double>("Longitude")
                        .HasColumnType("double precision");

                    b.Property<double?>("Odometer")
                        .HasColumnType("double precision");

                    b.Property<double?>("Speed")
                        .HasColumnType("double precision");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Timestamp");

                    b.HasIndex("DriveId", "Timestamp");

                    b.ToTable("Positions");
                });

            modelBuilder.Entity("RivianMate.Core.Entities.RivianAccount", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DisplayName")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("EncryptedAccessToken")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)");

                    b.Property<string>("EncryptedAppSessionToken")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)");

                    b.Property<string>("EncryptedCsrfToken")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)");

                    b.Property<string>("EncryptedRefreshToken")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)");

                    b.Property<string>("EncryptedUserSessionToken")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("LastSyncAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LastSyncError")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("RivianEmail")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("RivianUserId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime?>("TokenExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.HasIndex("UserId", "RivianEmail")
                        .IsUnique();

                    b.ToTable("RivianAccounts");
                });

            modelBuilder.Entity("RivianMate.Core.Entities.Setting", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsEncrypted")
                        .HasColumnType("boolean");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Value")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)");

                    b.HasKey("Id");

                    b.HasIndex("Key")
                        .IsUnique();

                    b.ToTable("Settings");
                });

            modelBuilder.Entity("RivianMate.Core.Entities.UserDashboardConfig", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("CardId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<bool>("IsVisible")
                        .HasColumnType("boolean");

                    b.Property<int>("Order")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.HasIndex("UserId", "CardId")
                        .IsUnique();

                    b.ToTable("UserDashboardConfigs");
                });

            modelBuilder.Entity("RivianMate.Core.Entities.UserLocation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsDefault")
                        .HasColumnType("boolean");

                    b.Property<double>("Latitude")
                        .HasColumnType("double precision");

                    b.Property<double>("Longitude")
                        .HasColumnType("double precision");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("UserLocations");
                });

            modelBuilder.Entity("RivianMate.Core.Entities.UserPreferences", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CurrencyCode")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)");

                    b.Property<int>("DistanceUnit")
                        .HasColumnType("integer");

                    b.Property<double?>("HomeElectricityRate")
                        .HasColumnType("double precision");

                    b.Property<double?>("HomeLatitude")
                        .HasColumnType("double precision");

                    b.Property<double?>("HomeLongitude")
                        .HasColumnType("double precision");

                    b.Property<int>("TemperatureUnit")
                        .HasColumnType("integer");

                    b.Property<string>("TimeZoneId")
                        .HasColumnType("text");

                    b.Property<int>("TirePressureUnit")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("UserPreferences");
                });

            modelBuilder.Entity("RivianMate.Core.Entities.Vehicle", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("BatteryCellType")
                        .HasColumnType("text");

                    b.Property<int>("BatteryPack")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("DriveType")
                        .HasColumnType("integer");

                    b.Property<double?>("EpaRangeMiles")
                        .HasColumnType("double precision");

                    b.Property<string>("ExteriorColor")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("ImageContentType")
                        .HasColumnType("text");

                    b.Property<byte[]>("ImageData")
                        .HasColumnType("bytea");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("text");

                    b.Property<int?>("ImageVersion")
                        .HasColumnType("integer");

                    b.Property<string>("InteriorColor")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("LastSeenAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Model")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<double?>("OriginalCapacityKwh")
                        .HasColumnType("double precision");

                    b.Property<Guid?>("OwnerId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("PublicId")
                        .HasColumnType("uuid");

                    b.Property<int?>("RivianAccountId")
                        .HasColumnType("integer");

                    b.Property<string>("RivianVehicleId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("SoftwareVersion")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int>("Trim")
                        .HasColumnType("integer");

                    b.Property<string>("Vin")
                        .HasMaxLength(17)
                        .HasColumnType("character varying(17)");

                    b.Property<string>("WheelConfig")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int?>("Year")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("OwnerId");

                    b.HasIndex("PublicId")
                        .IsUnique();

                    b.HasIndex("RivianAccountId");

                    b.HasIndex("RivianVehicleId")
                        .IsUnique();

                    b.HasIndex("Vin");

                    b.ToTable("Vehicles");
                });

            modelBuilder.Entity("RivianMate.Core.Entities.VehicleState", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("ActiveDriverName")
                        .HasColumnType("text");

                    b.Property<bool?>("AllDoorsClosed")
                        .HasColumnType("boolean");

                    b.Property<bool?>("AllDoorsLocked")
                        .HasColumnType("boolean");

                    b.Property<bool?>("AllWindowsClosed")
                        .HasColumnType("boolean");

                    b.Property<double?>("Altitude")
                        .HasColumnType("double precision");

                    b.Property<double?>("BatteryCapacityKwh")
                        .HasColumnType("double precision");

                    b.Property<string>("BatteryCellType")
                        .HasColumnType("text");

                    b.Property<double?>("BatteryLevel")
                        .HasColumnType("double precision");

                    b.Property<double?>("BatteryLimit")
                        .HasColumnType("double precision");

                    b.Property<bool?>("BatteryNeedsLfpCalibration")
                        .HasColumnType("boolean");

                    b.Property<double?>("CabinTemperature")
                        .HasColumnType("double precision");

                    b.Property<bool?>("ChargePortOpen")
                        .HasColumnType("boolean");

                    b.Property<string>("ChargerDerateStatus")
                        .HasColumnType("text");

                    b.Property<int>("ChargerState")
                        .HasColumnType("integer");

                    b.Property<double?>("ClimateTargetTemp")
                        .HasColumnType("double precision");

                    b.Property<string>("DriveMode")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<bool?>("FrunkClosed")
                        .HasColumnType("boolean");

                    b.Property<bool?>("FrunkLocked")
                        .HasColumnType("boolean");

                    b.Property<string>("GearGuardStatus")
                        .HasColumnType("text");

                    b.Property<int>("GearStatus")
                        .HasColumnType("integer");

                    b.Property<double?>("Heading")
                        .HasColumnType("double precision");

                    b.Property<bool?>("IsDefrostActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsInServiceMode")
                        .HasColumnType("boolean");

                    b.Property<bool?>("IsPetModeActive")
                        .HasColumnType("boolean");

                    b.Property<bool?>("IsPreconditioningActive")
                        .HasColumnType("boolean");

                    b.Property<double?>("Latitude")
                        .HasColumnType("double precision");

                    b.Property<bool?>("LiftgateClosed")
                        .HasColumnType("boolean");

                    b.Property<bool?>("LimitedAccelCold")
                        .HasColumnType("boolean");

                    b.Property<bool?>("LimitedRegenCold")
                        .HasColumnType("boolean");

                    b.Property<double?>("Longitude")
                        .HasColumnType("double precision");

                    b.Property<double?>("Odometer")
                        .HasColumnType("double precision");

                    b.Property<string>("OtaAvailableVersion")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("OtaCurrentVersion")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int?>("OtaInstallProgress")
                        .HasColumnType("integer");

                    b.Property<string>("OtaStatus")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int>("PowerState")
                        .HasColumnType("integer");

                    b.Property<double?>("ProjectedRangeAt100")
                        .HasColumnType("double precision");

                    b.Property<double?>("RangeEstimate")
                        .HasColumnType("double precision");

                    b.Property<string>("RawJson")
                        .HasColumnType("text");

                    b.Property<bool?>("SideBinLeftClosed")
                        .HasColumnType("boolean");

                    b.Property<bool?>("SideBinLeftLocked")
                        .HasColumnType("boolean");

                    b.Property<bool?>("SideBinRightClosed")
                        .HasColumnType("boolean");

                    b.Property<bool?>("SideBinRightLocked")
                        .HasColumnType("boolean");

                    b.Property<double?>("Speed")
                        .HasColumnType("double precision");

                    b.Property<bool?>("TailgateClosed")
                        .HasColumnType("boolean");

                    b.Property<int?>("TimeToEndOfCharge")
                        .HasColumnType("integer");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("timestamp with time zone");

                    b.Property<double?>("TirePressureFrontLeft")
                        .HasColumnType("double precision");

                    b.Property<double?>("TirePressureFrontRight")
                        .HasColumnType("double precision");

                    b.Property<double?>("TirePressureRearLeft")
                        .HasColumnType("double precision");

                    b.Property<double?>("TirePressureRearRight")
                        .HasColumnType("double precision");

                    b.Property<int>("TirePressureStatusFrontLeft")
                        .HasColumnType("integer");

                    b.Property<int>("TirePressureStatusFrontRight")
                        .HasColumnType("integer");

                    b.Property<int>("TirePressureStatusRearLeft")
                        .HasColumnType("integer");

                    b.Property<int>("TirePressureStatusRearRight")
                        .HasColumnType("integer");

                    b.Property<bool?>("TonneauClosed")
                        .HasColumnType("boolean");

                    b.Property<string>("TwelveVoltBatteryHealth")
                        .HasColumnType("text");

                    b.Property<int>("VehicleId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Timestamp");

                    b.HasIndex("VehicleId");

                    b.HasIndex("VehicleId", "Timestamp");

                    b.ToTable("VehicleStates");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.HasOne("RivianMate.Core.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.HasOne("RivianMate.Core.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RivianMate.Core.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.HasOne("RivianMate.Core.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("RivianMate.Core.Entities.ActivityFeedItem", b =>
                {
                    b.HasOne("RivianMate.Core.Entities.Vehicle", "Vehicle")
                        .WithMany("ActivityFeed")
                        .HasForeignKey("VehicleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Vehicle");
                });

            modelBuilder.Entity("RivianMate.Core.Entities.BatteryHealthSnapshot", b =>
                {
                    b.HasOne("RivianMate.Core.Entities.Vehicle", "Vehicle")
                        .WithMany("BatteryHealthSnapshots")
                        .HasForeignKey("VehicleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Vehicle");
                });

            modelBuilder.Entity("RivianMate.Core.Entities.BroadcastEmail", b =>
                {
                    b.HasOne("RivianMate.Core.Entities.ApplicationUser", "AdminUser")
                        .WithMany()
                        .HasForeignKey("AdminUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("AdminUser");
                });

            modelBuilder.Entity("RivianMate.Core.Entities.ChargingSession", b =>
                {
                    b.HasOne("RivianMate.Core.Entities.Vehicle", "Vehicle")
                        .WithMany("ChargingSessions")
                        .HasForeignKey("VehicleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Vehicle");
                });

            modelBuilder.Entity("RivianMate.Core.Entities.Drive", b =>
                {
                    b.HasOne("RivianMate.Core.Entities.Vehicle", "Vehicle")
                        .WithMany("Drives")
                        .HasForeignKey("VehicleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Vehicle");
                });

            modelBuilder.Entity("RivianMate.Core.Entities.Position", b =>
                {
                    b.HasOne("RivianMate.Core.Entities.Drive", "Drive")
                        .WithMany("Positions")
                        .HasForeignKey("DriveId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Drive");
                });

            modelBuilder.Entity("RivianMate.Core.Entities.RivianAccount", b =>
                {
                    b.HasOne("RivianMate.Core.Entities.ApplicationUser", "User")
                        .WithMany("RivianAccounts")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("RivianMate.Core.Entities.UserDashboardConfig", b =>
                {
                    b.HasOne("RivianMate.Core.Entities.ApplicationUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("RivianMate.Core.Entities.UserLocation", b =>
                {
                    b.HasOne("RivianMate.Core.Entities.ApplicationUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("RivianMate.Core.Entities.UserPreferences", b =>
                {
                    b.HasOne("RivianMate.Core.Entities.ApplicationUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("RivianMate.Core.Entities.Vehicle", b =>
                {
                    b.HasOne("RivianMate.Core.Entities.ApplicationUser", "Owner")
                        .WithMany("Vehicles")
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("RivianMate.Core.Entities.RivianAccount", "RivianAccount")
                        .WithMany("Vehicles")
                        .HasForeignKey("RivianAccountId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Owner");

                    b.Navigation("RivianAccount");
                });

            modelBuilder.Entity("RivianMate.Core.Entities.VehicleState", b =>
                {
                    b.HasOne("RivianMate.Core.Entities.Vehicle", "Vehicle")
                        .WithMany("States")
                        .HasForeignKey("VehicleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Vehicle");
                });

            modelBuilder.Entity("RivianMate.Core.Entities.ApplicationUser", b =>
                {
                    b.Navigation("RivianAccounts");

                    b.Navigation("Vehicles");
                });

            modelBuilder.Entity("RivianMate.Core.Entities.Drive", b =>
                {
                    b.Navigation("Positions");
                });

            modelBuilder.Entity("RivianMate.Core.Entities.RivianAccount", b =>
                {
                    b.Navigation("Vehicles");
                });

            modelBuilder.Entity("RivianMate.Core.Entities.Vehicle", b =>
                {
                    b.Navigation("ActivityFeed");

                    b.Navigation("BatteryHealthSnapshots");

                    b.Navigation("ChargingSessions");

                    b.Navigation("Drives");

                    b.Navigation("States");
                });
#pragma warning restore 612, 618
        }
    }
}
