// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using RivianMate.Infrastructure.Data;

#nullable disable

namespace RivianMate.Infrastructure.Migrations
{
    [DbContext(typeof(RivianMateDbContext))]
    [Migration("20260117193949_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.DataProtection.EntityFrameworkCore.DataProtectionKey", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("FriendlyName")
                        .HasColumnType("text");

                    b.Property<string>("Xml")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("DataProtectionKeys");
                });

            modelBuilder.Entity("RivianMate.Core.Entities.BatteryHealthSnapshot", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<double>("CapacityLostKwh")
                        .HasColumnType("double precision");

                    b.Property<double>("DegradationPercent")
                        .HasColumnType("double precision");

                    b.Property<double?>("DegradationRatePer10kMiles")
                        .HasColumnType("double precision");

                    b.Property<double>("HealthPercent")
                        .HasColumnType("double precision");

                    b.Property<double>("Odometer")
                        .HasColumnType("double precision");

                    b.Property<double>("OriginalCapacityKwh")
                        .HasColumnType("double precision");

                    b.Property<double?>("ProjectedHealthAt100kMiles")
                        .HasColumnType("double precision");

                    b.Property<double?>("ProjectedMilesTo70Percent")
                        .HasColumnType("double precision");

                    b.Property<double?>("RemainingWarrantyCapacityKwh")
                        .HasColumnType("double precision");

                    b.Property<double>("ReportedCapacityKwh")
                        .HasColumnType("double precision");

                    b.Property<double?>("StateOfCharge")
                        .HasColumnType("double precision");

                    b.Property<double?>("Temperature")
                        .HasColumnType("double precision");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("VehicleId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Timestamp");

                    b.HasIndex("VehicleId", "Timestamp");

                    b.ToTable("BatteryHealthSnapshots");
                });

            modelBuilder.Entity("RivianMate.Core.Entities.ChargingSession", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<double?>("AveragePowerKw")
                        .HasColumnType("double precision");

                    b.Property<double?>("CalculatedCapacityKwh")
                        .HasColumnType("double precision");

                    b.Property<double?>("CapacityConfidence")
                        .HasColumnType("double precision");

                    b.Property<double?>("ChargeLimit")
                        .HasColumnType("double precision");

                    b.Property<int>("ChargeType")
                        .HasColumnType("integer");

                    b.Property<double?>("EndBatteryLevel")
                        .HasColumnType("double precision");

                    b.Property<double?>("EndRangeEstimate")
                        .HasColumnType("double precision");

                    b.Property<DateTime?>("EndTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<double?>("EnergyAddedKwh")
                        .HasColumnType("double precision");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool?>("IsHomeCharging")
                        .HasColumnType("boolean");

                    b.Property<double?>("Latitude")
                        .HasColumnType("double precision");

                    b.Property<string>("LocationName")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<double?>("Longitude")
                        .HasColumnType("double precision");

                    b.Property<double?>("OdometerAtStart")
                        .HasColumnType("double precision");

                    b.Property<double?>("PeakPowerKw")
                        .HasColumnType("double precision");

                    b.Property<double?>("RangeAdded")
                        .HasColumnType("double precision");

                    b.Property<double>("StartBatteryLevel")
                        .HasColumnType("double precision");

                    b.Property<double?>("StartRangeEstimate")
                        .HasColumnType("double precision");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<double?>("TemperatureAtStart")
                        .HasColumnType("double precision");

                    b.Property<int>("VehicleId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("IsActive");

                    b.HasIndex("StartTime");

                    b.HasIndex("VehicleId", "StartTime");

                    b.ToTable("ChargingSessions");
                });

            modelBuilder.Entity("RivianMate.Core.Entities.Drive", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<double?>("AverageSpeedMph")
                        .HasColumnType("double precision");

                    b.Property<double?>("AverageTemperature")
                        .HasColumnType("double precision");

                    b.Property<double?>("DistanceMiles")
                        .HasColumnType("double precision");

                    b.Property<string>("DriveMode")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<double?>("EfficiencyMilesPerKwh")
                        .HasColumnType("double precision");

                    b.Property<double?>("EfficiencyWhPerMile")
                        .HasColumnType("double precision");

                    b.Property<double?>("ElevationGain")
                        .HasColumnType("double precision");

                    b.Property<string>("EndAddress")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<double?>("EndBatteryLevel")
                        .HasColumnType("double precision");

                    b.Property<double?>("EndElevation")
                        .HasColumnType("double precision");

                    b.Property<double?>("EndLatitude")
                        .HasColumnType("double precision");

                    b.Property<double?>("EndLongitude")
                        .HasColumnType("double precision");

                    b.Property<double?>("EndOdometer")
                        .HasColumnType("double precision");

                    b.Property<double?>("EndRangeEstimate")
                        .HasColumnType("double precision");

                    b.Property<DateTime?>("EndTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<double?>("EnergyUsedKwh")
                        .HasColumnType("double precision");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<double?>("MaxSpeedMph")
                        .HasColumnType("double precision");

                    b.Property<string>("StartAddress")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<double>("StartBatteryLevel")
                        .HasColumnType("double precision");

                    b.Property<double?>("StartElevation")
                        .HasColumnType("double precision");

                    b.Property<double?>("StartLatitude")
                        .HasColumnType("double precision");

                    b.Property<double?>("StartLongitude")
                        .HasColumnType("double precision");

                    b.Property<double>("StartOdometer")
                        .HasColumnType("double precision");

                    b.Property<double?>("StartRangeEstimate")
                        .HasColumnType("double precision");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("VehicleId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("IsActive");

                    b.HasIndex("StartTime");

                    b.HasIndex("VehicleId", "StartTime");

                    b.ToTable("Drives");
                });

            modelBuilder.Entity("RivianMate.Core.Entities.Position", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<double?>("Altitude")
                        .HasColumnType("double precision");

                    b.Property<double?>("BatteryLevel")
                        .HasColumnType("double precision");

                    b.Property<int>("DriveId")
                        .HasColumnType("integer");

                    b.Property<double?>("Heading")
                        .HasColumnType("double precision");

                    b.Property<double>("Latitude")
                        .HasColumnType("double precision");

                    b.Property<double>("Longitude")
                        .HasColumnType("double precision");

                    b.Property<double?>("Odometer")
                        .HasColumnType("double precision");

                    b.Property<double?>("Speed")
                        .HasColumnType("double precision");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Timestamp");

                    b.HasIndex("DriveId", "Timestamp");

                    b.ToTable("Positions");
                });

            modelBuilder.Entity("RivianMate.Core.Entities.Setting", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsEncrypted")
                        .HasColumnType("boolean");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Value")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)");

                    b.HasKey("Id");

                    b.HasIndex("Key")
                        .IsUnique();

                    b.ToTable("Settings");
                });

            modelBuilder.Entity("RivianMate.Core.Entities.Vehicle", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("BatteryPack")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("DriveType")
                        .HasColumnType("integer");

                    b.Property<double?>("EpaRangeMiles")
                        .HasColumnType("double precision");

                    b.Property<string>("ExteriorColor")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("InteriorColor")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("LastSeenAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Model")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<double?>("OriginalCapacityKwh")
                        .HasColumnType("double precision");

                    b.Property<string>("RivianVehicleId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("SoftwareVersion")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Vin")
                        .HasMaxLength(17)
                        .HasColumnType("character varying(17)");

                    b.Property<string>("WheelConfig")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int?>("Year")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("RivianVehicleId")
                        .IsUnique();

                    b.HasIndex("Vin");

                    b.ToTable("Vehicles");
                });

            modelBuilder.Entity("RivianMate.Core.Entities.VehicleState", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<bool?>("AllDoorsClosed")
                        .HasColumnType("boolean");

                    b.Property<bool?>("AllDoorsLocked")
                        .HasColumnType("boolean");

                    b.Property<bool?>("AllWindowsClosed")
                        .HasColumnType("boolean");

                    b.Property<double?>("Altitude")
                        .HasColumnType("double precision");

                    b.Property<double?>("BatteryCapacityKwh")
                        .HasColumnType("double precision");

                    b.Property<double?>("BatteryLevel")
                        .HasColumnType("double precision");

                    b.Property<double?>("BatteryLimit")
                        .HasColumnType("double precision");

                    b.Property<double?>("CabinTemperature")
                        .HasColumnType("double precision");

                    b.Property<int>("ChargerState")
                        .HasColumnType("integer");

                    b.Property<double?>("ClimateTargetTemp")
                        .HasColumnType("double precision");

                    b.Property<string>("DriveMode")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<bool?>("FrunkClosed")
                        .HasColumnType("boolean");

                    b.Property<bool?>("FrunkLocked")
                        .HasColumnType("boolean");

                    b.Property<bool?>("GearGuardEnabled")
                        .HasColumnType("boolean");

                    b.Property<int>("GearStatus")
                        .HasColumnType("integer");

                    b.Property<double?>("Heading")
                        .HasColumnType("double precision");

                    b.Property<bool?>("IsDefrostActive")
                        .HasColumnType("boolean");

                    b.Property<bool?>("IsPetModeActive")
                        .HasColumnType("boolean");

                    b.Property<bool?>("IsPreconditioningActive")
                        .HasColumnType("boolean");

                    b.Property<double?>("Latitude")
                        .HasColumnType("double precision");

                    b.Property<bool?>("LiftgateClosed")
                        .HasColumnType("boolean");

                    b.Property<double?>("Longitude")
                        .HasColumnType("double precision");

                    b.Property<double?>("Odometer")
                        .HasColumnType("double precision");

                    b.Property<string>("OtaAvailableVersion")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("OtaCurrentVersion")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int?>("OtaInstallProgress")
                        .HasColumnType("integer");

                    b.Property<string>("OtaStatus")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int>("PowerState")
                        .HasColumnType("integer");

                    b.Property<double?>("ProjectedRangeAt100")
                        .HasColumnType("double precision");

                    b.Property<double?>("RangeEstimate")
                        .HasColumnType("double precision");

                    b.Property<string>("RawJson")
                        .HasColumnType("text");

                    b.Property<double?>("Speed")
                        .HasColumnType("double precision");

                    b.Property<int?>("TimeToEndOfCharge")
                        .HasColumnType("integer");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("TirePressureFrontLeft")
                        .HasColumnType("integer");

                    b.Property<int>("TirePressureFrontRight")
                        .HasColumnType("integer");

                    b.Property<int>("TirePressureRearLeft")
                        .HasColumnType("integer");

                    b.Property<int>("TirePressureRearRight")
                        .HasColumnType("integer");

                    b.Property<bool?>("TonneauClosed")
                        .HasColumnType("boolean");

                    b.Property<int>("VehicleId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Timestamp");

                    b.HasIndex("VehicleId", "Timestamp");

                    b.ToTable("VehicleStates");
                });

            modelBuilder.Entity("RivianMate.Core.Entities.BatteryHealthSnapshot", b =>
                {
                    b.HasOne("RivianMate.Core.Entities.Vehicle", "Vehicle")
                        .WithMany("BatteryHealthSnapshots")
                        .HasForeignKey("VehicleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Vehicle");
                });

            modelBuilder.Entity("RivianMate.Core.Entities.ChargingSession", b =>
                {
                    b.HasOne("RivianMate.Core.Entities.Vehicle", "Vehicle")
                        .WithMany("ChargingSessions")
                        .HasForeignKey("VehicleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Vehicle");
                });

            modelBuilder.Entity("RivianMate.Core.Entities.Drive", b =>
                {
                    b.HasOne("RivianMate.Core.Entities.Vehicle", "Vehicle")
                        .WithMany("Drives")
                        .HasForeignKey("VehicleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Vehicle");
                });

            modelBuilder.Entity("RivianMate.Core.Entities.Position", b =>
                {
                    b.HasOne("RivianMate.Core.Entities.Drive", "Drive")
                        .WithMany("Positions")
                        .HasForeignKey("DriveId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Drive");
                });

            modelBuilder.Entity("RivianMate.Core.Entities.VehicleState", b =>
                {
                    b.HasOne("RivianMate.Core.Entities.Vehicle", "Vehicle")
                        .WithMany("States")
                        .HasForeignKey("VehicleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Vehicle");
                });

            modelBuilder.Entity("RivianMate.Core.Entities.Drive", b =>
                {
                    b.Navigation("Positions");
                });

            modelBuilder.Entity("RivianMate.Core.Entities.Vehicle", b =>
                {
                    b.Navigation("BatteryHealthSnapshots");

                    b.Navigation("ChargingSessions");

                    b.Navigation("Drives");

                    b.Navigation("States");
                });
#pragma warning restore 612, 618
        }
    }
}
