// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RivianMate.Infrastructure.Data;

#nullable disable

namespace RivianMate.Infrastructure.Migrations
{
    [DbContext(typeof(RivianMateDbContext))]
    partial class RivianMateDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.11");

            modelBuilder.Entity("Microsoft.AspNetCore.DataProtection.EntityFrameworkCore.DataProtectionKey", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("FriendlyName")
                        .HasColumnType("TEXT");

                    b.Property<string>("Xml")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("DataProtectionKeys");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ClaimType")
                        .HasColumnType("TEXT");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ClaimType")
                        .HasColumnType("TEXT");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("UserId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("UserId")
                        .HasColumnType("TEXT");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("TEXT");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("TEXT");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<string>("Value")
                        .HasColumnType("TEXT");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("RivianMate.Core.Entities.ApplicationUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("DisplayName")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("LastLoginAt")
                        .HasColumnType("TEXT");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("TEXT");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("TEXT");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("TEXT");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("RivianMate.Core.Entities.BatteryHealthSnapshot", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double>("CapacityLostKwh")
                        .HasColumnType("REAL");

                    b.Property<double>("DegradationPercent")
                        .HasColumnType("REAL");

                    b.Property<double?>("DegradationRatePer10kMiles")
                        .HasColumnType("REAL");

                    b.Property<double>("HealthPercent")
                        .HasColumnType("REAL");

                    b.Property<double>("Odometer")
                        .HasColumnType("REAL");

                    b.Property<double>("OriginalCapacityKwh")
                        .HasColumnType("REAL");

                    b.Property<double?>("ProjectedHealthAt100kMiles")
                        .HasColumnType("REAL");

                    b.Property<double?>("ProjectedMilesTo70Percent")
                        .HasColumnType("REAL");

                    b.Property<double?>("RemainingWarrantyCapacityKwh")
                        .HasColumnType("REAL");

                    b.Property<double>("ReportedCapacityKwh")
                        .HasColumnType("REAL");

                    b.Property<double?>("StateOfCharge")
                        .HasColumnType("REAL");

                    b.Property<double?>("Temperature")
                        .HasColumnType("REAL");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("TEXT");

                    b.Property<int>("VehicleId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("Timestamp");

                    b.HasIndex("VehicleId", "Timestamp");

                    b.ToTable("BatteryHealthSnapshots");
                });

            modelBuilder.Entity("RivianMate.Core.Entities.ChargingSession", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double?>("AveragePowerKw")
                        .HasColumnType("REAL");

                    b.Property<double?>("CalculatedCapacityKwh")
                        .HasColumnType("REAL");

                    b.Property<double?>("CapacityConfidence")
                        .HasColumnType("REAL");

                    b.Property<double?>("ChargeLimit")
                        .HasColumnType("REAL");

                    b.Property<int>("ChargeType")
                        .HasColumnType("INTEGER");

                    b.Property<double?>("Cost")
                        .HasColumnType("REAL");

                    b.Property<string>("DriveMode")
                        .HasColumnType("TEXT");

                    b.Property<double?>("EndBatteryLevel")
                        .HasColumnType("REAL");

                    b.Property<double?>("EndRangeEstimate")
                        .HasColumnType("REAL");

                    b.Property<DateTime?>("EndTime")
                        .HasColumnType("TEXT");

                    b.Property<double?>("EnergyAddedKwh")
                        .HasColumnType("REAL");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<bool?>("IsHomeCharging")
                        .HasColumnType("INTEGER");

                    b.Property<double?>("Latitude")
                        .HasColumnType("REAL");

                    b.Property<string>("LocationName")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<double?>("Longitude")
                        .HasColumnType("REAL");

                    b.Property<double?>("OdometerAtStart")
                        .HasColumnType("REAL");

                    b.Property<double?>("PeakPowerKw")
                        .HasColumnType("REAL");

                    b.Property<double?>("RangeAdded")
                        .HasColumnType("REAL");

                    b.Property<double>("StartBatteryLevel")
                        .HasColumnType("REAL");

                    b.Property<double?>("StartRangeEstimate")
                        .HasColumnType("REAL");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("TEXT");

                    b.Property<double?>("TemperatureAtStart")
                        .HasColumnType("REAL");

                    b.Property<int>("VehicleId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("IsActive");

                    b.HasIndex("StartTime");

                    b.HasIndex("VehicleId", "StartTime");

                    b.ToTable("ChargingSessions");
                });

            modelBuilder.Entity("RivianMate.Core.Entities.Drive", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double?>("AverageSpeedMph")
                        .HasColumnType("REAL");

                    b.Property<double?>("AverageTemperature")
                        .HasColumnType("REAL");

                    b.Property<double?>("DistanceMiles")
                        .HasColumnType("REAL");

                    b.Property<string>("DriveMode")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<double?>("EfficiencyMilesPerKwh")
                        .HasColumnType("REAL");

                    b.Property<double?>("EfficiencyWhPerMile")
                        .HasColumnType("REAL");

                    b.Property<double?>("ElevationGain")
                        .HasColumnType("REAL");

                    b.Property<string>("EndAddress")
                        .HasMaxLength(300)
                        .HasColumnType("TEXT");

                    b.Property<double?>("EndBatteryLevel")
                        .HasColumnType("REAL");

                    b.Property<double?>("EndElevation")
                        .HasColumnType("REAL");

                    b.Property<double?>("EndLatitude")
                        .HasColumnType("REAL");

                    b.Property<double?>("EndLongitude")
                        .HasColumnType("REAL");

                    b.Property<double?>("EndOdometer")
                        .HasColumnType("REAL");

                    b.Property<double?>("EndRangeEstimate")
                        .HasColumnType("REAL");

                    b.Property<DateTime?>("EndTime")
                        .HasColumnType("TEXT");

                    b.Property<double?>("EnergyUsedKwh")
                        .HasColumnType("REAL");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<double?>("MaxSpeedMph")
                        .HasColumnType("REAL");

                    b.Property<string>("StartAddress")
                        .HasMaxLength(300)
                        .HasColumnType("TEXT");

                    b.Property<double>("StartBatteryLevel")
                        .HasColumnType("REAL");

                    b.Property<double?>("StartElevation")
                        .HasColumnType("REAL");

                    b.Property<double?>("StartLatitude")
                        .HasColumnType("REAL");

                    b.Property<double?>("StartLongitude")
                        .HasColumnType("REAL");

                    b.Property<double>("StartOdometer")
                        .HasColumnType("REAL");

                    b.Property<double?>("StartRangeEstimate")
                        .HasColumnType("REAL");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("TEXT");

                    b.Property<int>("VehicleId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("IsActive");

                    b.HasIndex("StartTime");

                    b.HasIndex("VehicleId", "StartTime");

                    b.ToTable("Drives");
                });

            modelBuilder.Entity("RivianMate.Core.Entities.Position", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double?>("Altitude")
                        .HasColumnType("REAL");

                    b.Property<double?>("BatteryLevel")
                        .HasColumnType("REAL");

                    b.Property<int>("DriveId")
                        .HasColumnType("INTEGER");

                    b.Property<double?>("Heading")
                        .HasColumnType("REAL");

                    b.Property<double>("Latitude")
                        .HasColumnType("REAL");

                    b.Property<double>("Longitude")
                        .HasColumnType("REAL");

                    b.Property<double?>("Odometer")
                        .HasColumnType("REAL");

                    b.Property<double?>("Speed")
                        .HasColumnType("REAL");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Timestamp");

                    b.HasIndex("DriveId", "Timestamp");

                    b.ToTable("Positions");
                });

            modelBuilder.Entity("RivianMate.Core.Entities.RivianAccount", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("DisplayName")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("EncryptedAccessToken")
                        .HasMaxLength(4000)
                        .HasColumnType("TEXT");

                    b.Property<string>("EncryptedAppSessionToken")
                        .HasMaxLength(4000)
                        .HasColumnType("TEXT");

                    b.Property<string>("EncryptedCsrfToken")
                        .HasMaxLength(4000)
                        .HasColumnType("TEXT");

                    b.Property<string>("EncryptedRefreshToken")
                        .HasMaxLength(4000)
                        .HasColumnType("TEXT");

                    b.Property<string>("EncryptedUserSessionToken")
                        .HasMaxLength(4000)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("LastSyncAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("LastSyncError")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<string>("RivianEmail")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("RivianUserId")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("TokenExpiresAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("UserId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.HasIndex("UserId", "RivianEmail")
                        .IsUnique();

                    b.ToTable("RivianAccounts");
                });

            modelBuilder.Entity("RivianMate.Core.Entities.Setting", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsEncrypted")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Value")
                        .HasMaxLength(4000)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Key")
                        .IsUnique();

                    b.ToTable("Settings");
                });

            modelBuilder.Entity("RivianMate.Core.Entities.UserDashboardConfig", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CardId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsVisible")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Order")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("UserId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.HasIndex("UserId", "CardId")
                        .IsUnique();

                    b.ToTable("UserDashboardConfigs");
                });

            modelBuilder.Entity("RivianMate.Core.Entities.Vehicle", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("BatteryCellType")
                        .HasColumnType("TEXT");

                    b.Property<int>("BatteryPack")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("DriveType")
                        .HasColumnType("INTEGER");

                    b.Property<double?>("EpaRangeMiles")
                        .HasColumnType("REAL");

                    b.Property<string>("ExteriorColor")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("ImageContentType")
                        .HasColumnType("TEXT");

                    b.Property<byte[]>("ImageData")
                        .HasColumnType("BLOB");

                    b.Property<int?>("ImageVersion")
                        .HasColumnType("INTEGER");

                    b.Property<string>("InteriorColor")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("LastSeenAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("Model")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<double?>("OriginalCapacityKwh")
                        .HasColumnType("REAL");

                    b.Property<Guid?>("OwnerId")
                        .HasColumnType("TEXT");

                    b.Property<int?>("RivianAccountId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("RivianVehicleId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("SoftwareVersion")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<int>("Trim")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Vin")
                        .HasMaxLength(17)
                        .HasColumnType("TEXT");

                    b.Property<string>("WheelConfig")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<int?>("Year")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("OwnerId");

                    b.HasIndex("RivianAccountId");

                    b.HasIndex("RivianVehicleId")
                        .IsUnique();

                    b.HasIndex("Vin");

                    b.ToTable("Vehicles");
                });

            modelBuilder.Entity("RivianMate.Core.Entities.VehicleState", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ActiveDriverName")
                        .HasColumnType("TEXT");

                    b.Property<bool?>("AllDoorsClosed")
                        .HasColumnType("INTEGER");

                    b.Property<bool?>("AllDoorsLocked")
                        .HasColumnType("INTEGER");

                    b.Property<bool?>("AllWindowsClosed")
                        .HasColumnType("INTEGER");

                    b.Property<double?>("Altitude")
                        .HasColumnType("REAL");

                    b.Property<double?>("BatteryCapacityKwh")
                        .HasColumnType("REAL");

                    b.Property<string>("BatteryCellType")
                        .HasColumnType("TEXT");

                    b.Property<double?>("BatteryLevel")
                        .HasColumnType("REAL");

                    b.Property<double?>("BatteryLimit")
                        .HasColumnType("REAL");

                    b.Property<bool?>("BatteryNeedsLfpCalibration")
                        .HasColumnType("INTEGER");

                    b.Property<double?>("CabinTemperature")
                        .HasColumnType("REAL");

                    b.Property<bool?>("ChargePortOpen")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ChargerDerateStatus")
                        .HasColumnType("TEXT");

                    b.Property<int>("ChargerState")
                        .HasColumnType("INTEGER");

                    b.Property<double?>("ClimateTargetTemp")
                        .HasColumnType("REAL");

                    b.Property<string>("DriveMode")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<bool?>("FrunkClosed")
                        .HasColumnType("INTEGER");

                    b.Property<bool?>("FrunkLocked")
                        .HasColumnType("INTEGER");

                    b.Property<bool?>("GearGuardEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<int>("GearStatus")
                        .HasColumnType("INTEGER");

                    b.Property<double?>("Heading")
                        .HasColumnType("REAL");

                    b.Property<bool?>("IsDefrostActive")
                        .HasColumnType("INTEGER");

                    b.Property<bool?>("IsPetModeActive")
                        .HasColumnType("INTEGER");

                    b.Property<bool?>("IsPreconditioningActive")
                        .HasColumnType("INTEGER");

                    b.Property<double?>("Latitude")
                        .HasColumnType("REAL");

                    b.Property<bool?>("LiftgateClosed")
                        .HasColumnType("INTEGER");

                    b.Property<bool?>("LimitedAccelCold")
                        .HasColumnType("INTEGER");

                    b.Property<bool?>("LimitedRegenCold")
                        .HasColumnType("INTEGER");

                    b.Property<double?>("Longitude")
                        .HasColumnType("REAL");

                    b.Property<double?>("Odometer")
                        .HasColumnType("REAL");

                    b.Property<string>("OtaAvailableVersion")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("OtaCurrentVersion")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<int?>("OtaInstallProgress")
                        .HasColumnType("INTEGER");

                    b.Property<string>("OtaStatus")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<int>("PowerState")
                        .HasColumnType("INTEGER");

                    b.Property<double?>("ProjectedRangeAt100")
                        .HasColumnType("REAL");

                    b.Property<double?>("RangeEstimate")
                        .HasColumnType("REAL");

                    b.Property<string>("RawJson")
                        .HasColumnType("TEXT");

                    b.Property<double?>("Speed")
                        .HasColumnType("REAL");

                    b.Property<int?>("TimeToEndOfCharge")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("TEXT");

                    b.Property<double?>("TirePressureFrontLeft")
                        .HasColumnType("REAL");

                    b.Property<double?>("TirePressureFrontRight")
                        .HasColumnType("REAL");

                    b.Property<double?>("TirePressureRearLeft")
                        .HasColumnType("REAL");

                    b.Property<double?>("TirePressureRearRight")
                        .HasColumnType("REAL");

                    b.Property<int>("TirePressureStatusFrontLeft")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TirePressureStatusFrontRight")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TirePressureStatusRearLeft")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TirePressureStatusRearRight")
                        .HasColumnType("INTEGER");

                    b.Property<bool?>("TonneauClosed")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TwelveVoltBatteryHealth")
                        .HasColumnType("TEXT");

                    b.Property<int>("VehicleId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("Timestamp");

                    b.HasIndex("VehicleId", "Timestamp");

                    b.ToTable("VehicleStates");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.HasOne("RivianMate.Core.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.HasOne("RivianMate.Core.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RivianMate.Core.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.HasOne("RivianMate.Core.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("RivianMate.Core.Entities.BatteryHealthSnapshot", b =>
                {
                    b.HasOne("RivianMate.Core.Entities.Vehicle", "Vehicle")
                        .WithMany("BatteryHealthSnapshots")
                        .HasForeignKey("VehicleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Vehicle");
                });

            modelBuilder.Entity("RivianMate.Core.Entities.ChargingSession", b =>
                {
                    b.HasOne("RivianMate.Core.Entities.Vehicle", "Vehicle")
                        .WithMany("ChargingSessions")
                        .HasForeignKey("VehicleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Vehicle");
                });

            modelBuilder.Entity("RivianMate.Core.Entities.Drive", b =>
                {
                    b.HasOne("RivianMate.Core.Entities.Vehicle", "Vehicle")
                        .WithMany("Drives")
                        .HasForeignKey("VehicleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Vehicle");
                });

            modelBuilder.Entity("RivianMate.Core.Entities.Position", b =>
                {
                    b.HasOne("RivianMate.Core.Entities.Drive", "Drive")
                        .WithMany("Positions")
                        .HasForeignKey("DriveId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Drive");
                });

            modelBuilder.Entity("RivianMate.Core.Entities.RivianAccount", b =>
                {
                    b.HasOne("RivianMate.Core.Entities.ApplicationUser", "User")
                        .WithMany("RivianAccounts")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("RivianMate.Core.Entities.UserDashboardConfig", b =>
                {
                    b.HasOne("RivianMate.Core.Entities.ApplicationUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("RivianMate.Core.Entities.Vehicle", b =>
                {
                    b.HasOne("RivianMate.Core.Entities.ApplicationUser", "Owner")
                        .WithMany("Vehicles")
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("RivianMate.Core.Entities.RivianAccount", "RivianAccount")
                        .WithMany("Vehicles")
                        .HasForeignKey("RivianAccountId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Owner");

                    b.Navigation("RivianAccount");
                });

            modelBuilder.Entity("RivianMate.Core.Entities.VehicleState", b =>
                {
                    b.HasOne("RivianMate.Core.Entities.Vehicle", "Vehicle")
                        .WithMany("States")
                        .HasForeignKey("VehicleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Vehicle");
                });

            modelBuilder.Entity("RivianMate.Core.Entities.ApplicationUser", b =>
                {
                    b.Navigation("RivianAccounts");

                    b.Navigation("Vehicles");
                });

            modelBuilder.Entity("RivianMate.Core.Entities.Drive", b =>
                {
                    b.Navigation("Positions");
                });

            modelBuilder.Entity("RivianMate.Core.Entities.RivianAccount", b =>
                {
                    b.Navigation("Vehicles");
                });

            modelBuilder.Entity("RivianMate.Core.Entities.Vehicle", b =>
                {
                    b.Navigation("BatteryHealthSnapshots");

                    b.Navigation("ChargingSessions");

                    b.Navigation("Drives");

                    b.Navigation("States");
                });
#pragma warning restore 612, 618
        }
    }
}
